
REFRESH_RATE = 0.01

MAX_SCREEN_WIDTH = 200
SCROLL_AMOUNT = 2

CURSOR_BLINK_INTERVAL = 1

NOTIFICATION_TIMEOUT = 5
TEST_NOTIFICATION = 'This is a test Notification'
I_LOVE_SARAH_NOTIFICATION = 'I lub Sarah soooooo much'
